Algoritmo "Temp"

Var

   temp, equi : real
   d : caractere
   
Inicio
   
   
   repita
         escreva ("Digite a temperatura em celsius : ")
         leia (temp)
         equi <- ((9 * temp) / 5) + 32
         escreval ("Equivalente em Fahrenheit: ", equi)
         escreva ("Deseja repetir (s/n) ?")
         leia (d)
   ate d = "n"
   

      
      



            

Fimalgoritmo